services:
  # services stack
  reverse_proxy:
    image: nginx:1.20.2
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx/custom.conf:/etc/nginx/conf.d/custom.conf
    depends_on:
      - app1
      - app2
  app1:
    image: nginx:1.20.2
    restart: always
    volumes:
      - ./html_app1:/usr/share/nginx/html
  app2:
    image: node:16.13.1-bullseye-slim
    deploy:
      replicas: 2
    restart: always
    expose:
      - 3000
    volumes:
      - ./html_app2:/usr/src/app
    working_dir: /usr/src/app
    command: [ 'npm', 'start' ]

  # services tools
  npm:
    image: node:16.13.1-bullseye-slim
    volumes:
      - ./html_app2:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: [ 'npm' ]
